name: "Upload zip-archive"
on:
  release:
    types: [published]

jobs:
  zip-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Create zip including submodules
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-${{ github.ref_name }}.zip ${{ github.event.repository.name }} -r
      - name: Upload zip to release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ github.event.repository.name }}-${{ github.ref_name }}.zip