name: "Build pull request"
on:
  #pull_request:
    #types: ['opened', 'synchronize']

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.3
      with: 
        submodules: true
    - name: Setup node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.12.1
        cache: 'npm'
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
    - name: Install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: Install cinny dependencies
      run: cd cinny && npm ci
    - name: Install tauri dependencies
      run: npm ci
    - name: Build desktop app with Tauri
      uses: tauri-apps/tauri-action@v0.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}